language: php

dist: trusty
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files
        - .phpunit

matrix:
    include:
        - php: hhvm
        - php: 5.6
        - php: 7.0
        - php: 7.1
          env: composer_extra="--prefer-lowest --prefer-stable"
    fast_finish: true

install:
    - composer $composer_extra update
    - composer require phpunit/phpunit ^5.7

script:
- ./vendor/bin/phpunit
